# Generated by Django 6.0.5 on 2026-05-16 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='scans/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('real', 'Secure / Valid'), ('fake', 'Threat / Deepfake'), ('modified', 'Altered / Warning')], default='real', max_length=10)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('system_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
