# Generated by Django 6.0.5 on 2026-05-18 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Forensic Audit Log', 'verbose_name_plural': 'Forensic Audit Ledger'},
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='engine_version',
            field=models.CharField(default='Neural Core v4.5', max_length=20),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='mime_type',
            field=models.CharField(default='image/png', max_length=50),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='processing_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Moderate Risk'), ('HIGH', 'Critical Threat')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Global Internal Identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='image',
            field=models.ImageField(help_text='Secure isolated storage for ingested binary', upload_to='vault/forensics/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='status',
            field=models.CharField(choices=[('REAL', 'AUTHENTIC IMAGE'), ('FAKE', 'DEEPFAKE DETECTED'), ('MODIFIED', 'MODIFIED ASSET')], default='REAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='system_hash',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
