from django.contrib import admin
from django.utils.html import format_html
from .models import ScanRecord

@admin.register(ScanRecord)
class ScanRecordAdmin(admin.ModelAdmin):
    """
    FORENSIC ADMINISTRATION CONSOLE
    Provides a high-level overview of all neural scans processed by the system.
    """

    # 1. LIST VIEW CONFIGURATION
    # These columns will appear in the main ledger table
    list_display = (
        'colored_status', 
        'file_name', 
        'confidence_score_pct', 
        'system_hash_display', 
        'created_at'
    )

    # 2. FILTER & SEARCH
    # Quick-access sidebar to narrow down results
    list_filter = ('status', 'created_at')
    
    # Allows searching by file name or the unique tracking hash
    search_fields = ('file_name', 'system_hash', 'id')

    # 3. DETAIL VIEW ORGANIZATION
    # Grouping fields into sections for a cleaner UI
    fieldsets = (
        ('Asset Information', {
            'fields': ('id', 'file_name', 'file_size', 'image')
        }),
        ('Neural Audit Results', {
            'fields': ('status', 'confidence_score', 'system_hash'),
            'description': 'Data generated by the DeepForensicScanner engine.'
        }),
        ('Temporal Metadata', {
            'fields': ('created_at',),
        }),
    )

    # 4. SECURITY & INTEGRITY
    # These fields cannot be edited manually in the admin to prevent audit tampering
    readonly_fields = ('id', 'created_at', 'system_hash', 'confidence_score')

    # 5. ELABORATED CUSTOM COLUMNS
    
    @admin.display(description='Forensic Verdict')
    def colored_status(self, obj):
        """
        Visual indicators for the scan status.
        Red = Threat (Fake), Orange = Altered (Modified), Green = Secure (Real)
        """
        colors = {
            'fake': '#ef4444',     # Alert Red
            'modified': '#f59e0b', # Warning Orange
            'real': '#10b981',     # Success Green
        }
        return format_html(
            '<span style="color: white; background-color: {}; padding: 3px 10px; '
            'border-radius: 12px; font-weight: bold; text-transform: uppercase; font-size: 10px;">{}</span>',
            colors.get(obj.status, '#6b7280'),
            obj.get_status_display()
        )

    @admin.display(description='Confidence')
    def confidence_score_pct(self, obj):
        """Displays the score with a percentage sign."""
        return f"{obj.confidence_score}%"

    @admin.display(description='Tracking Hash')
    def system_hash_display(self, obj):
        """Displays the hash in a monospace font for a technical look."""
        if obj.system_hash:
            return format_html('<code>{}</code>', obj.system_hash)
        return "-"

    # Set the default ordering to show newest scans first
    ordering = ('-created_at',)