from rest_framework import serializers
from .models import ScanRecord

class ScanRecordSerializer(serializers.ModelSerializer):
    """
    Automates conversion between JSON and Database models.
    Includes built-in security validation for file ingestion.
    """
    
    # Generated by system logic, not user input
    status = serializers.CharField(read_only=True)
    confidence_score = serializers.FloatField(read_only=True)
    system_hash = serializers.CharField(read_only=True)
    created_at = serializers.DateTimeField(format="%Y-%m-%d %H:%M", read_only=True)

    class Meta:
        model = ScanRecord
        fields = '__all__'

    def validate_image(self, value):
        """
        Security: Ensure ingested binary doesn't exceed 10MB 
        to prevent memory overflow in neural buffers.
        """
        limit = 10 * 1024 * 1024 # 10MB
        if value.size > limit:
            raise serializers.ValidationError("Matrix Ingestion Error: File size exceeds 10MB limit.")
        return value