import random
import time
import uuid
import logging

# Django & Rest Framework Imports
from django.db import transaction
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework import status

# Internal Project Imports
from .models import ScanRecord
from .serializers import ScanRecordSerializer

# Initialize Logger for Forensic Auditing
logger = logging.getLogger(__name__)

class DeepForensicScanner(APIView):
    """
    ==========================================================================
    AI VISION GUARD - NEURAL FORENSIC INGESTION ENGINE
    ==========================================================================
    This controller handles the multi-stage lifecycle of a digital asset scan:
    1. INGESTION: Binary file stream extraction via MultiPartParser.
    2. VALIDATION: Structural integrity and metadata checks via Serializer.
    3. ANALYSIS: Neural matrix evaluation (Simulated for this implementation).
    4. LEDGERING: Cryptographic-style recording into the database.
    5. REPORTING: Discrepancy feedback returned to the React frontend.
    """
    
    # Allows the view to accept file uploads (FormData) from the React frontend
    parser_classes = (MultiPartParser, FormParser)

    def post(self, request, *args, **kwargs):
        """
        Ingest a new forensic sample and perform a structural audit.
        """
        logger.info("Forensic Ingestion Started: Processing raw binary stream.")

        # 1. INITIALIZE DATA INGESTION
        # We pass the request data (image, name, size) into our serializer
        serializer = ScanRecordSerializer(data=request.data)
        
        # 2. VALIDATION LAYER
        # This triggers the 'validate_image' check in serializers.py (max 10MB)
        if not serializer.is_valid():
            logger.warning(f"Ingestion Rejected: Validation constraints failed. Errors: {serializer.errors}")
            return Response({
                "status": "INGESTION_ERROR",
                "message": "The uploaded asset does not meet security protocols.",
                "errors": serializer.errors
            }, status=status.HTTP_400_BAD_REQUEST)

        try:
            # 3. COMPUTATIONAL ANALYSIS PHASE (The Neural Audit)
            # Use atomic transactions to ensure database integrity if the analysis fails
            with transaction.atomic():
                
                # --- [SIMULATED NEURAL ENGINE START] ---
                # In a production environment, this is where you would call:
                # model_prediction = ForensicModel.predict(request.FILES['image'])
                
                # We simulate 'Network Latency' for the UI spinner in React
                time.sleep(1.5) 
                
                # Generate a high-precision confidence score (10.0 to 99.8)
                score = round(random.uniform(10.0, 99.8), 1)
                
                # Classification Matrix Logic
                # REAL: No GAN artifacts detected
                # MODIFIED: Metadata conflicts or ELA discrepancies found
                # FAKE: High probability of generative neural synthesis
                if score > 82:
                    audit_status = 'real'
                    risk_level = 'Low'
                elif score > 45:
                    audit_status = 'modified'
                    risk_level = 'Medium'
                else:
                    audit_status = 'fake'
                    risk_level = 'High'

                # Generate a unique forensic system hash for tracking
                unique_hash = f"SHA-{str(uuid.uuid4())[:8].upper()}"
                # --- [SIMULATED NEURAL ENGINE END] ---

                # 4. DATABASE LEDGER RECORDING
                # Save the validated file plus the results generated by our "Engine"
                scan_instance = serializer.save(
                    status=audit_status,
                    confidence_score=score,
                    system_hash=unique_hash
                )

                logger.info(f"Audit Complete: ID {scan_instance.id} saved with status {audit_status}")

                # 5. CONSTRUCT FORENSIC REPORT RESPONSE
                # This object is mapped exactly to the 'scanResult' state in React
                return Response({
                    "id": str(scan_instance.id),
                    "system_hash": scan_instance.system_hash,
                    "file_name": scan_instance.file_name,
                    "status": audit_status.upper() if audit_status != 'real' else "AUTHENTIC IMAGE",
                    "type": audit_status.upper(), # Required for React History Filters
                    "confidence_score": scan_instance.confidence_score,
                    "score": scan_instance.confidence_score, # Alias for frontend UI
                    "risk": risk_level,
                    "threat": risk_level, # Alias for report UI
                    "timestamp": scan_instance.created_at.strftime("%b %d, %Y"),
                    "created_at": scan_instance.created_at.strftime("%Y-%m-%d %H:%M"),
                    "metadata": {
                        "device": "Neural Forensic Array v4.5 (Verified)",
                        "location": "Secure Distributed Node 142",
                        "edited": "High Structural Modification" if audit_status != 'real' else "No Deviations Detected",
                        "node_hash": str(uuid.uuid4())[:13].upper()
                    }
                }, status=status.HTTP_201_CREATED)

        except Exception as e:
            logger.error(f"Critical System Failure: {str(e)}")
            return Response({
                "status": "CRITICAL_FAILURE",
                "message": "The neural processing unit encountered a matrix error.",
                "trace": str(e) if True else "Internal Server Error" 
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def get(self, request):
        """
        FETCH GLOBAL LEDGER
        Provides data for the 'Activity Ledger' table in the React dashboard.
        Supports ordering by the latest scan.
        """
        try:
            # Retrieve the most recent 50 scans to populate the ledger
            records = ScanRecord.objects.all().order_by('-created_at')[:50]
            
            # Serialize the data for JSON transmission
            serializer = ScanRecordSerializer(records, many=True)
            
            # We transform the data slightly to match the React Table Row expectations
            # (Adding 'name', 'type', 'date' aliases)
            formatted_data = []
            for item in serializer.data:
                formatted_data.append({
                    "id": item.get('system_hash'),
                    "db_id": item.get('id'), # Actual UUID
                    "name": item.get('file_name'),
                    "type": item.get('status').upper(),
                    "score": item.get('confidence_score'),
                    "date": item.get('created_at'),
                    "threat": "High" if item.get('status') == 'fake' else "Medium" if item.get('status') == 'modified' else "Low"
                })

            return Response(formatted_data, status=status.HTTP_200_OK)

        except Exception as e:
            return Response({"error": "Failed to retrieve audit ledger."}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def delete(self, request, pk=None):
        """
        PURGE RECORD
        Allows for manual removal of a forensic trace from the system ledger.
        """
        try:
            record = ScanRecord.objects.get(pk=pk)
            record.delete()
            return Response({"status": "SUCCESS", "message": "Forensic trace purged."}, status=status.HTTP_204_NO_CONTENT)
        except ScanRecord.DoesNotExist:
            return Response({"status": "ERROR", "message": "Record not found."}, status=status.HTTP_404_NOT_FOUND)